stages:
  - deploy

variables:
  DEPLOY_DIR: "/var/www/html"

deploy_wordpress:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add git wget tar bash
  script:
    # Clone your GitHub repo
    - git clone https://github.com/vamokaha/tsa-assessment.git site-code
    - cd site-code

    # Download WordPress if not already included
    - wget https://wordpress.org/latest.tar.gz
    - tar -xvzf latest.tar.gz
    - mv wordpress/* $DEPLOY_DIR/
    - rm -rf wordpress latest.tar.gz

    # Copy custom repo files (themes, plugins, config)
    - cp -r * $DEPLOY_DIR/

    # Set permissions
    - chmod -R 755 $DEPLOY_DIR
    - chown -R www-data:www-data $DEPLOY_DIR
  only:
    - main
